FROM node:14-alpine AS PROD
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.19-alpine AS SERVER
COPY ./etc/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=PROD /app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]