version: "3"

services:
  app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    environment:
      # - REACT_APP_NAME=Rajesh-Dev
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env
