version: "3"

services:
  app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    environment:
      # - REACT_APP_NAME=Rajesh-Prod
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env
